In [1]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/curahHujan_db"
)

In [2]:
df_ch = pd.read_sql("""
SELECT station, date + time AS timestamp, rainfall
FROM rainfall
ORDER BY station, timestamp
""", engine)

In [3]:
df_tma = pd.read_sql("""
SELECT station, date + time AS timestamp, water_level
FROM tma
ORDER BY station, timestamp
""", engine)

In [4]:
df_ch_per_station = {
    st: df.reset_index(drop=True)
    for st, df in df_ch.groupby("station")
}

In [5]:
start_date = "2025-02-01"

for st in df_ch_per_station:
    df = df_ch_per_station[st]
    
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    
    df = df[df["timestamp"] >= start_date]
    
    df_ch_per_station[st] = df

In [6]:
df_tma["timestamp"] = pd.to_datetime(df_tma["timestamp"])
df_tma = df_tma[df_tma["timestamp"] >= start_date]

In [7]:
import numpy as np

df_tma.loc[df_tma["water_level"] <= 0, "water_level"] = np.nan
df_tma.loc[df_tma["water_level"] > 4.5, "water_level"] = np.nan

In [8]:
THRESHOLD = 50

for st in df_ch_per_station:
    df = df_ch_per_station[st]
    df.loc[df["rainfall"] > THRESHOLD, "rainfall"] = np.nan
    df_ch_per_station[st] = df

In [9]:
for st in df_ch_per_station:
    df_ch_per_station[st] = df_ch_per_station[st].copy()
    df_ch_per_station[st]["timestamp"] = pd.to_datetime(
        df_ch_per_station[st]["timestamp"]
    )
    df_ch_per_station[st] = df_ch_per_station[st].set_index("timestamp")

In [10]:
ch_all = pd.concat(
    {st: df["rainfall"] for st, df in df_ch_per_station.items()},
    axis=1
)
ch_all["ch_mean"] = ch_all.sum(axis=1)

In [11]:
df_tma = df_tma.copy()
df_tma["timestamp"] = pd.to_datetime(df_tma["timestamp"])
df_tma = df_tma.set_index("timestamp")

In [12]:
import numpy as np

max_lag = 36
results_station = {}

for st in ch_all.columns.drop("ch_mean", errors="ignore"):
    
    corrs = []
    
    for lag in range(max_lag):
        corr = df_tma["water_level"].corr(
            ch_all[st].shift(lag)
        )
        corrs.append(corr)
    
    corrs = np.array(corrs)
    
    best_lag = corrs.argmax()
    best_corr = corrs.max()
    
    results_station[st] = (best_lag, best_corr)

In [13]:
for st, (lag, corr) in results_station.items():
    print(f"{st}: lag={lag} ({lag*10} menit), corr={corr:.3f}")

Cihawuk: lag=21 (210 menit), corr=0.234
Cikitu: lag=16 (160 menit), corr=0.274
Ibun: lag=13 (130 menit), corr=0.340
Kertasari: lag=18 (180 menit), corr=0.235
Nagrak: lag=17 (170 menit), corr=0.059
Paseh Cipaku: lag=12 (120 menit), corr=0.194

In [14]:
best_lags = {
    "Cihawuk": 21,
    "Cikitu": 16,
    "Ibun": 13,
    "Kertasari": 18,
    "Nagrak": 17,
    "Paseh Cipaku": 12
}

In [15]:
ch_lagged = pd.DataFrame(index=ch_all.index)

for st, lag in best_lags.items():
    ch_lagged[st] = ch_all[st].shift(lag)

In [16]:
ch_lagged

                     Cihawuk  Cikitu  Ibun  Kertasari  Nagrak  Paseh Cipaku
timestamp
2025-02-01 00:00:00      NaN     NaN   NaN        NaN     NaN           NaN
2025-02-01 00:10:00      NaN     NaN   NaN        NaN     NaN           NaN
2025-02-01 00:20:00      NaN     NaN   NaN        NaN     NaN           NaN
2025-02-01 00:30:00      NaN     NaN   NaN        NaN     NaN           NaN
2025-02-01 00:40:00      NaN     NaN   NaN        NaN     NaN           NaN
...                      ...     ...   ...        ...     ...           ...
2026-02-12 13:40:00      0.0     0.0   0.0        0.0     NaN           0.0
2026-02-12 13:50:00      0.0     0.0   0.0        0.0     NaN           0.0
2026-02-12 14:00:00      0.0     0.0   0.0        0.0     NaN           0.0
2026-02-12 14:10:00      0.0     0.0   0.0        0.0     NaN           0.0
2026-02-12 14:20:00      0.0     0.5   0.0        0.0     NaN           0.0

[54231 rows x 6 columns]

In [18]:
nan_df = pd.DataFrame({
    "NaN (%)": [
        ch_lagged[st].isna().mean() * 100
        for st in ch_lagged.columns
    ]
}, index=ch_lagged.columns)

nan_df

                NaN (%)
Cihawuk        0.516310
Cikitu        30.194907
Ibun          54.144309
Kertasari      0.593756
Nagrak         9.241946
Paseh Cipaku   0.580849